name: 'Build with cargo-zigbuild'
description: 'Github Action to build Cargo project with cargo-zigbuild'
author: 'hominsu'

branding:
  icon: 'settings'
  color: 'gray-dark'

inputs:
  workdir:
    description: "Working directory of cargo/cargo-zigbuild execution"
    required: false
    default: '.'
  outdir:
    description: "Output directory for the build artifacts"
    required: false
    default: './artifacts'
  name:
    description: "Name of binary to compile"
    required: true
  args:
    description: "Arguments to pass to cargo/cargo-zigbuild"
    required: true
  github-token:
    description: "API token used to authenticate to a Git repository for remote definitions"
    default: ${{ github.token }}
    required: false

runs:
  using: node20
  main: dist/index.js
